# Generated by Django 3.0.7 on 2021-05-31 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(max_length=50)),
                ('email_template', models.FileField(upload_to='email_templates/')),
            ],
            options={
                'verbose_name_plural': 'Email Templates',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=50)),
                ('notification_template', models.CharField(max_length=140)),
            ],
            options={
                'verbose_name_plural': 'Notification Template',
            },
        ),
        migrations.CreateModel(
            name='TermAndConditionAndPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'T&C and Privacy Policy',
            },
        ),
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=150)),
                ('type_id', models.CharField(max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification History',
            },
        ),
        migrations.CreateModel(
            name='NotificationEmailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_follows_me', models.BooleanField(default=True)),
                ('e_follows_me', models.BooleanField(default=True)),
                ('n_like_my_activity', models.BooleanField(default=True)),
                ('e_like_my_activity', models.BooleanField(default=True)),
                ('n_comment_my_activity', models.BooleanField(default=True)),
                ('e_comment_my_activity', models.BooleanField(default=True)),
                ('n_any_other_activity', models.BooleanField(default=True)),
                ('e_any_other_activity', models.BooleanField(default=True)),
                ('n_occasional_updates', models.BooleanField(default=True)),
                ('e_occasional_updates', models.BooleanField(default=True)),
                ('n_chat_notification', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_time', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notification_and_mails.EmailTemplates')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Email History',
            },
        ),
    ]
