# Generated by Django 3.0.7 on 2021-06-01 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('seen', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('message_from', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_from', to=settings.AUTH_USER_MODEL)),
                ('message_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
