# Generated by Django 3.0.7 on 2021-05-31 12:07

import coins_and_gifts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_thumbnail', models.ImageField(default='audio_categories/default_audio.png', null=True, upload_to=coins_and_gifts.models.AudioCategories.get_upload_path)),
                ('audio_category', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=140)),
            ],
            options={
                'verbose_name_plural': 'Audio Categories',
            },
        ),
        migrations.CreateModel(
            name='CoinManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Coin Management',
            },
        ),
        migrations.CreateModel(
            name='GiftManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_name', models.CharField(max_length=50)),
                ('gift', models.FileField(upload_to='gifts/')),
                ('coin_cost', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Gift Management',
            },
        ),
        migrations.CreateModel(
            name='headingandpoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('points', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Heading And Points',
            },
        ),
        migrations.CreateModel(
            name='StickerManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticker_name', models.CharField(max_length=50)),
                ('sticker', models.FileField(upload_to='stickers/')),
                ('sticker_type', models.CharField(choices=[('H', 'Hashtags'), ('C', 'Cities'), ('B', 'Badges')], default='H', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Sticker Management',
            },
        ),
        migrations.CreateModel(
            name='UserRefer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='referred', to=settings.AUTH_USER_MODEL)),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Referred User',
            },
        ),
        migrations.CreateModel(
            name='ReferralId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Referral Code of Users',
            },
        ),
        migrations.CreateModel(
            name='GiftTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_message', models.CharField(default=None, max_length=140, null=True)),
                ('time_of_gifting', models.DateTimeField(auto_now_add=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('gift_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coins_and_gifts.GiftManagement')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gift_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gift_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Gift Transactions',
            },
        ),
        migrations.CreateModel(
            name='CoinTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('coin_count', models.IntegerField()),
                ('sender_rem_balance', models.IntegerField()),
                ('receiver_rem_balance', models.IntegerField()),
                ('time_of_transaction', models.DateTimeField(auto_now_add=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver_id', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Coin Transactions',
            },
        ),
        migrations.CreateModel(
            name='CoinRedeemTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_amount', models.IntegerField()),
                ('cash_amount', models.IntegerField()),
                ('redeem_time', models.DateTimeField(auto_now_add=True)),
                ('redeemed_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Coin Redeem Transactions',
            },
        ),
        migrations.CreateModel(
            name='AudioManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_name', models.CharField(max_length=50)),
                ('audio', models.FileField(upload_to='audios/')),
                ('coin_cost', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('audio_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coins_and_gifts.AudioCategories')),
            ],
            options={
                'verbose_name_plural': 'Audio Management',
            },
        ),
    ]
